import express from "express";import {createServer} from "node:http";import {WebSocketServer} from "ws";import path from "node:path";import {fileURLToPath} from "node:url";
const app=express(),http=createServer(app),wss=new WebSocketServer({server:http,path:"/ws"}),clients=new Set();app.use(express.json());
let live={id:"LIVE",name:"LIVE-01",lat:-60,lon:0,status:"normal",battery:92,batteryV:12.6,solarW:18,sst:-1.2,salinity:34.2,hs:2.3,tp:9.4,wd:215,wind:18,air:-4,pressure:1004,signal:88,internal:4.1,drift:0,lastUpdate:Date.now()};
function sim(i){let t=Date.now()/1000,b=48+40*(.5+.5*Math.sin(t/1100+i)),fault=i===13&&Math.floor(t/50)%9===3,off=i===27&&Math.floor(t/90)%8===4;return{id:`PB-${String(i+1).padStart(2,"0")}`,name:`PB-${String(i+1).padStart(2,"0")}`,lat:-52-(i%8)*2.3+Math.sin(t/180+i)*.04,lon:((i*37.7+Math.sin(t/240+i)*1.5+180)%360)-180,status:off?"offline":fault?"fault":b<22?"low":"normal",battery:b,batteryV:11.8+b*.01,solarW:Math.max(0,22+12*Math.sin(t/300+i)),sst:-1.6+.9*Math.sin(i+t/900)+(i===19?-5*Math.max(0,Math.sin(t/50)):0),salinity:33.8+.8*Math.sin(i),hs:1.2+2.4*(.5+.5*Math.sin(t/170+i)),tp:6+7*(.5+.5*Math.sin(t/280+i)),wd:(i*29+t*.2)%360,wind:8+28*(.5+.5*Math.sin(t/200+i)),air:-3-8*(.5+.5*Math.sin(t/600+i)),pressure:990+25*(.5+.5*Math.sin(t/500+i)),signal:55+45*(.5+.5*Math.sin(t/250+i)),internal:1+7*(.5+.5*Math.sin(t/700+i)),drift:Math.sin(t/500+i)*1.8,lastUpdate:Date.now()}}
function all(){return [...Array(40)].map((_,i)=>sim(i)).concat([{...live,lastUpdate:Date.now()}])}
wss.on("connection",ws=>{clients.add(ws);ws.send(JSON.stringify({type:"telemetry",buoys:all()}));ws.on("close",()=>clients.delete(ws))});
setInterval(()=>{let m=JSON.stringify({type:"telemetry",buoys:all()});for(const w of clients)if(w.readyState===1)w.send(m)},2000);
app.post("/api/ingest",(req,res)=>{if(typeof req.body.lat!=="number"||typeof req.body.lon!=="number")return res.status(400).json({error:"lat and lon required"});live={...live,...req.body,id:"LIVE",name:req.body.name||"LIVE-01",status:"normal",lastUpdate:Date.now()};res.json({ok:true,buoy:live})});
app.get("/api/grid",(req,res)=>res.json({generatedAt:Date.now(),grid:[...Array(9)].flatMap((_,a)=>[...Array(37)].map((_,o)=>({lat:-50-a*2.5,lon:-180+o*10,u:5+8*Math.sin((o*10+a)*.03),v:2+5*Math.cos(o*.04)})))}));
app.get("/api/export/:id",(req,res)=>{let b=all().find(x=>x.id===req.params.id)||live,r=["timestamp,id,lat,lon,sst,salinity,hs,tp,battery,solarW,wind,air,pressure"];for(let i=0;i<720;i++){let t=Date.now()-i*120000;r.push([new Date(t).toISOString(),b.id,b.lat,b.lon,b.sst,b.salinity,b.hs,b.tp,b.battery,b.solarW,b.wind,b.air,b.pressure].join(","))}res.type("text/csv").send(r.join("\n"))});
const dist=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../dist");app.use(express.static(dist));app.use((q,s)=>s.sendFile(path.join(dist,"index.html")));http.listen(3001,()=>console.log("PolarBuoy backend on 3001"));